name:                metaLampServer
version:             0.1.0.0
github:              "githubuser/metaLampServer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/metaLampServer#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-multipart
- servant-server
- warp
- wai
- http-types
- esqueleto
- persistent
- time
- bytestring
- persistent-postgresql
- persistent-template
- configurator
- transformers
# postgresql-simple brings in the scope SqlError which is used for exception handling
- postgresql-simple
- monad-logger
- katip
- wai-extra
- aeson
- text
- containers
- cryptonite
- base64-bytestring
- word8
- mtl
- directory
- exceptions

library:
  source-dirs: src
  default-extensions: 
    - OverloadedStrings

executables:
  metaLampServer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metaLampServer

tests:
  metaLampServer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metaLampServer
